### File name: Supplement 5_Zill et al 2023_Data analysis code.R
### Script for eel survey data analysis
### Contact: Julie Zill, jzill@hawaii.edu

### To cite paper: 
### Zill, J.A., R. Kosaki, and M.J. Donahue. 2023. "Moray eels inconspicuously predominate heavily fished reefs." Ecology.

### For an explanation of data variables, column names, and their units, see metadata file:
## Supplement 1_Zill et al 2023_Metadata_Variables_AllDataFiles.csv

### Required data files:
## Supplement 2_Zill et al 2023_Data by survey.csv
## Supplement 3_Zill et al 2023_Data by eel record.csv
## Supplement 4_Zill et al 2023_Data_Common species_Count by survey.csv

## Set working direction to the folder containing the above .csv data files 
# setwd("~/Downloads")


## Load required libraries
## --------------------------------------------------
#install.packages("plyr")
library("plyr")
#install.packages("tidyverse", dependencies=TRUE)
library("tidyverse")
#install.packages("lmerTest") 
library("lmerTest") #Function: anova()
#install.packages("lme4") 
library("lme4") #Function: lmer()
#install.packages("reshape2") 
library("reshape2") #Function: melt()


## Load data
## --------------------------------------------------
#Load survey-level data
surveydata <- read_csv("Supplement 2_Zill et al 2023_Data by survey.csv", col_names = TRUE, na = c("", "N/A", "NA"), skip_empty_rows=TRUE) #imports data as a dataframe
#Convert quantitative variables to numeric format
cols_numeric <- c("6":"34")
surveydata[cols_numeric] <- sapply(surveydata[cols_numeric],as.numeric)
#add Eel biomass : Non-eel mesopredator biomass ratio data needed for Model 4
surveydata <- surveydata %>% mutate(Ratio_Eels_to_OtherMesopreds_Biomass = (1 + Eel_biomass_g_m2) / (1 + Non_eel_mesopredator_biomass_g_m2))

#Load EelID-level data (data by individual eel)
eeldata <- read_csv("Supplement 3_Zill et al 2023_Data by eel record.csv", col_names = TRUE, na = c("", "N/A", "NA"), skip_empty_rows=TRUE) #imports data as a dataframe

#Load abundance data: count of common species per survey
countdata <- read_csv("Supplement 4_Zill et al 2023_Data_Common species_Count by survey.csv", col_names = TRUE, na = c("", "N/A", "NA"), skip_empty_rows=TRUE) #imports data as a dataframe

#Add habitat complexity and water flow covariate data to eeldata and countdata
covars <- surveydata %>% select(SurveyNum, 
                                Chain_rugosity_ratio,
                                Insitu_observer_complexity_rating,
                                Max_substrate_height_m,
                                Mean_substrate_height_m,
                                Mean_substrate_height_bin_variability_m,
                                Insitu_observer_complexity_rating,
                                ADCP_flow_rate_m_s,
                                Fluorescein_plume_diameter_1min_m,
                                Fluorescein_plume_diameter_3min_m,
                                Clod_card_dissolution_time_s)
eeldata <- left_join(eeldata, covars, by=c("SurveyNum")) 
countdata <- left_join(countdata, covars, by=c("SurveyNum")) 

## Data Analysis
##--------------------------------------------------
### Comparison of eel biomass between MHI surveys with and without additional chum packets deployed: T-test
#Extract the eel biomass densities of the 6 Main Hawaiian Island surveys that had chum packets
chum <- surveydata %>% 
  filter(SurveyNum %in% 1:6) %>%
  select(Eel_biomass_g_m2)
chum <- as.numeric(chum$Eel_biomass_g_m2)

#Extract the eel biomass densities of the MHI surveys that did not have chum packets
nochum <- surveydata %>% #List of eel biomass (total g per survey before 40mins of soak time) of subsequent Oahu and HI surveys that had no chum
  subset(SurveyNum %in% c(7:29,58:60)) %>% 
  select(Eel_biomass_g_m2) 
nochum <- as.numeric(nochum$Eel_biomass_g_m2)

#Use a Fisher's F-test to see if the variances are equal
var.test(chum, nochum) #p = 0.1486 (indicates variances are equal; use var.equal = TRUE in the t-test)
t.test(chum, nochum, var.equal = TRUE) #t = 0.15977, df = 30, p-value = 0.8741
##--------------------------------------------------


### Model 1: Piscivore biomass between regions
# This model uses publically available SPC survey data provided by the Pacific Reef Assessment and Monitoring Program
# of the NOAA Ecosystem Science Division, available at:
# https://www.fisheries.noaa.gov/inport/item/24447

# Further information and the R code used to subset and manipulate raw SPC data into site-level data are available through:
# Heenan, A., Williams, I., Acoba, T., DesRochers, A., Kosaki, R., Kanemura, T., Nadon, M., Brainard, R. (2017) Long term monitoring of coral reef fish assemblages in the Western Central Pacific. Scientific Data 

# Model used on "wsd", a subsetted dataframe generated by the R code provided by Heenan et al. 2017:
# m1 <- lmer(log10(Piscivore_biomass_g_m2 + 1) ~ Region + (1|Moku), data=wsd) 

### Model output:
# summary(m1)
# Linear mixed model fit by REML. t-tests use Satterthwaite's method ['lmerModLmerTest']
# Formula: log10(Piscivore_biomass_g_m2 + 1) ~ Region + (1 | Moku)
#    Data: wsd
# 
# REML criterion at convergence: 2453
# 
# Scaled residuals: 
#     Min      1Q  Median      3Q     Max 
# -2.7860 -0.5055 -0.0914  0.6410  3.7766 
# 
# Random effects:
#  Groups   Name        Variance Std.Dev.
#  MOKU     (Intercept) 0.05748  0.2398  
#  Residual             0.32771  0.5725  
# Number of obs: 1377, groups:  MOKU, 50
# 
# Fixed effects:
#             Estimate Std. Error       df t value Pr(>|t|)    
# (Intercept)  0.43819    0.04473 46.18877   9.797 7.45e-13 ***
# REGIONNWHI   0.80080    0.09677 40.10451   8.275 3.30e-10 ***
# ---
# Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1
# 
# Correlation of Fixed Effects:
#            (Intr)
# REGIONNWHI -0.462

#Backtransformations for m1 results, which were log10(x+1) transformed: 
(10^0.43819)-1 #p=7.45e-13. MHI effect = 1.742774 on natural scale
(10^(0.43819+0.80080))-1 #p=3.30e-10. NWHI effect = 16.33764 on natural scale
16.33764/1.742774 #9.374503. Piscivore biomass was 9.4x higher in NWHI, on natural scale

# anova(m1)
# Type III Analysis of Variance Table with Satterthwaite's method
#        Sum Sq Mean Sq NumDF  DenDF F value    Pr(>F)    
# REGION 22.441  22.441     1 40.105  68.477 3.296e-10 ***
# ---
# Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1



### Model 2: Eel biomass between regions
m2 <- lmer(log10(Eel_biomass_g_m2 + 1) ~ Region + (1|Moku), data=surveydata)
summary(m2)
anova(m2)
#Backtransformations: 
(10^0.91528)-1 #p=0.000636. MHI effect is 7.227729 on the natural scale.
(10^(0.91528-0.51594))-1 #p=0.006864. NWHI effect is 1.508072 on the natural scale.
7.227729/1.508072 #Eel biomass was 4.792695 times higher in the MHI than the NWHI.


### Model 3: Eel biomass across a gradient of apex predator (non-eel pisciviore of 40+ cm body length) biomass
m3 <- lmer(log10(Eel_biomass_g_m2 + 1) ~ log10(1 + Apex_predator_biomass_g_m2) + (1|Moku), data=surveydata)
summary(m3)

### Model 4:
#Ratio was calculated above and added to dataframe. Ratio_Eels_to_OtherMesopreds_Biomass = (1 + Eel_biomass_g_m2) / (1 + Non_eel_mesopredator_biomass_g_m2)
m4 <- lmer(log10(Ratio_Eels_to_OtherMesopreds_Biomass) ~ log10(Total_fish_biomass_g_m2) + (1|Moku), data=surveydata)
summary(m4)

### Model 5:
subset <- eeldata %>% 
  filter(Observed_before_40_mins=="1"&(Species=="Gymnothorax eurostus"|Species=="Gymnothorax flavimarginatus"|Species=="Gymnothorax meleagris"|Species=="Gymnothorax undulatus"))
m5 <- lmer(Total_body_length_cm ~ Region + Species + Region:Species + Species*Mean_substrate_height_bin_variability_m + (1|Moku/SurveyNum), data=subset)
summary(m5)
anova(m5)

### Model 6:
m6 <- glm(CountPerSurvey ~ Region + Species + Region:Species + Insitu_observer_complexity_rating, family=poisson, data=countdata)
summary(m6)


